### ISSUE TITLE
What is the technology stack behind the website?

### ISSUE THREAD

**Issue by Yura52** [poyo-brain/poyo-brain.github.io#3]
Hi! I have just encountered this website presenting the work "A Unified, Scalable Framework for Neural Population Decoding", and the website looks really great stylistically (unfortunately, I cannot understand the paper itself due to a completely different expertise 😄)! I wonder what is the technology stack behind it? (I assumed that it was not written manually but rather generated from markdown-like source code)

**Comment by vinamarora8** [comment]
Thanks, glad you liked the website! This is just manually written HTML, CSS, JS :P

**Comment by Yura52** [comment]
Really like it :) Thanks for the reply!

**Comment by mazabou** [comment]
For the interactive visuals, we used both bokeh and threeJS!
